COPY INTO ANALYTICS_DEV.BRONZE.USERS
FROM @analytics_dev.raw.azuredata_stage/users/
FILE_FORMAT = 'ANALYTICS_DEV.RAW.FF_USERS_CSV'
INCLUDE_METADATA = (
    SourceFilePath        = METADATA$FILENAME,
    SourceFileRowNumber   = METADATA$FILE_ROW_NUMBER,
    SourceFileLastModified = METADATA$FILE_LAST_MODIFIED,
    LoadTs                = METADATA$START_SCAN_TIME
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
VALIDATION_MODE = RETURN_ERRORS;